# create spring postgresql properties
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 10000ms
    database: 0
  cache:
    type: redis
    redis:
      time-to-live: 30
      cache-null-values: false