version: '3.1'
services:
  db:
    image: "postgres"
    container_name: "db"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
        - "5432:5432"
    volumes:
        - ./data/postgres:/var/lib/postgresql/data
  cache:
    image: "redis"
    container_name: "cache"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
